function gh=simview(scenario);

%% close all related windows
h = findobj('Tag','SimWindow');
delete(h);
h = findobj('Tag','EditorWindow');
delete(h);

%% Create a new simulator figure
gh.figNumber = figure;

ssize = get(0,'ScreenSize');
set(gh.figNumber,	'MenuBar','none',...
    'CloseRequestFcn','simviewcb close',...
    'Position',[1 ssize(4)*0.13 ssize(3)/2 ssize(4)*0.8],...
    'NumberTitle','off',...
    'Name','Simulation Window',...
    'RendererMode','manual',...
    'Renderer','Painters',...
    'Backingstore','off',...
    'Tag','SimWindow');

%% add the background picture
gh.axHndl=gca;
hold on;
axis equal;
axis off;
color = get(gh.figNumber,'Color');
matrix=imread(scenario.bmp_name,'bmp');
for j=1:3
    matrix_aux(:,:,j) = flipud(matrix(:,:,j));
end
[xmax, ymax] = size(matrix_aux);
gh.axHndl=image(matrix_aux,'Parent',gh.axHndl);
set(gh.axHndl, 'Tag','SimAxes');

%% add elements
gh.StepText = uicontrol('Parent',gh.figNumber, ...
    'Units','points', ...
    'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
    'FontWeight','bold',...
    'ListboxTop',0, ...
    'Position',[ssize(3)/2-250 10*ssize(3)/800 40 10], ...
    'String','Step', ...
    'Style','text', ...
    'Tag','StepText');
                  
                 
%% Window Menu
gh.menu.main = uimenu('Label','&File');
gh.menu.open = uimenu('Parent',gh.menu.main,'Label','&Open ..','Callback','simviewcb load',...
    'Accelerator','O');
gh.menu.open= uimenu('Parent',gh.menu.main,'Label','&Save ..','Callback','simviewcb save',...
    'Enable','off','Accelerator','S','Tag','SaveMenu');
gh.menu.close = uimenu('Parent',gh.menu.main,'Label','&Close ..','Callback','simviewcb close',...
    'Accelerator','O');

gh.runmenu.main = uimenu('Label','&Run','Enable','off','Tag','WinRunMenu');
gh.runmenu.StopMenu=uimenu('Parent',gh.runmenu.main,'Label','S&top','Accelerator','T',...
    'Callback','simviewcb stop','Tag','StopMenu','Enable','off',...
    'Separator','on');
gh.runmenu.StartMenu=uimenu('Parent',gh.runmenu.main,'Label','S&tart','Accelerator','T',...
    'Callback','simviewcb init','Tag','StartMenu','Enable','on',...
    'Separator','on');

save gh;