###################################################
# FAMOUSO related stuff                           #
###################################################

# provide the location where is FAMOUSO
FAMOUSO_INSTALLDIR = ../..

# You can choose the platform on which FAMOUSO
# is used.
#
# supported platforms:
#     -linux
#     -linux/openwrt
#     -windows/cross-mingw
#     -windows/native-mingw
#     -avr
#
# e.g. FAMOUSO_CONFIG= linux
#
# If you left it unset the current value from
# FAMOUSO_INSTALLDIR/make/config.mk is chosen.

# You can also set the generation of DEBUG messages by setting the
# FAMOUSO_DEBUG variable. If you set it e.g. to "FAMOUSO_DEBUG=" no debugging
# information are generated by the compiler, but the normal debugging output of
# FAMOUSO is generated.  Switching this off too, you should use:
# FAMOUSO_DEBUG=-DNDEBUG

# include famouso externals makefile which sets all
# relevant variables that are needed to build correctly
# against FAMOUSO
include $(FAMOUSO_INSTALLDIR)/make/famouso_as_external_lib.mk

# The following variables contain the right includes,
# libs, preprocessor settings, ...
# The names are self-explanatory and the variables
# should be used within own defined compiling-rules.
$(info $(FAMOUSO_COMPILER_OPTIONS_MUST_HAVE))
$(info $(FAMOUSO_COMPILER_OPTIONS_SUGGESTED))

###################################################
# Your Makefile instructions and rules start here #
###################################################
all:
	@echo
