function scenario=manipulate(scenario)

if etime(clock,scenario.startTime)>length(scenario.robots) && length(scenario.robots)<5
    sensors.name='sensor_1';
    sensors.position=[5 0];
    sensors.axisangle=0;
    sensors.scanangle=120;
    sensors.range=20;
    sensors.resolution=30;
    sensors.line=0;

    aux=length(scenario.robots);

    addrobot=simrobot('robot_2',...
        aux+1,...
        90,...
        1,...
        'robot_1_app',...
        [1 1 0],...
        1,...
        [-2 0 4 0 -2],...
        [3 4 0 -4 -3],...
        sensors, ...
        [100+aux*30 200]);
    addrobot=activate(addrobot);
    scenario.robots(aux+1)=addrobot;
    disp('Scenario adapted ...')
end