# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'virtual_sensor.ui'
#
# Created: Fri Jan 21 16:49:17 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(600, 274)
        Frame.setFrameShape(QtGui.QFrame.StyledPanel)
        Frame.setFrameShadow(QtGui.QFrame.Raised)
        self.verticalLayoutWidget = QtGui.QWidget(Frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 401, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_X = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_X.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_X.setObjectName("label_X")
        self.horizontalLayout.addWidget(self.label_X)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.sliderX = QtGui.QSlider(self.verticalLayoutWidget)
        self.sliderX.setMinimum(-500)
        self.sliderX.setMaximum(500)
        self.sliderX.setOrientation(QtCore.Qt.Horizontal)
        self.sliderX.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderX.setTickInterval(50)
        self.sliderX.setObjectName("sliderX")
        self.verticalLayout.addWidget(self.sliderX)
        self.verticalLayoutWidget_2 = QtGui.QWidget(Frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 80, 401, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.label_Y = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_Y.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Y.setObjectName("label_Y")
        self.horizontalLayout_2.addWidget(self.label_Y)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.sliderY = QtGui.QSlider(self.verticalLayoutWidget_2)
        self.sliderY.setMinimum(-500)
        self.sliderY.setMaximum(500)
        self.sliderY.setOrientation(QtCore.Qt.Horizontal)
        self.sliderY.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderY.setTickInterval(50)
        self.sliderY.setObjectName("sliderY")
        self.verticalLayout_2.addWidget(self.sliderY)
        self.verticalLayoutWidget_3 = QtGui.QWidget(Frame)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 140, 401, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.label_Z = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_Z.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Z.setObjectName("label_Z")
        self.horizontalLayout_3.addWidget(self.label_Z)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.sliderZ = QtGui.QSlider(self.verticalLayoutWidget_3)
        self.sliderZ.setMinimum(-500)
        self.sliderZ.setMaximum(500)
        self.sliderZ.setOrientation(QtCore.Qt.Horizontal)
        self.sliderZ.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderZ.setTickInterval(50)
        self.sliderZ.setObjectName("sliderZ")
        self.verticalLayout_3.addWidget(self.sliderZ)
        self.pushButton_Connect = QtGui.QPushButton(Frame)
        self.pushButton_Connect.setGeometry(QtCore.QRect(440, 210, 151, 51))
        self.pushButton_Connect.setObjectName("pushButton_Connect")
        self.verticalLayoutWidget_4 = QtGui.QWidget(Frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(440, 20, 151, 171))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dial = QtGui.QDial(self.verticalLayoutWidget_4)
        self.dial.setMinimumSize(QtCore.QSize(0, 144))
        self.dial.setWrapping(False)
        self.dial.setObjectName("dial")
        self.verticalLayout_4.addWidget(self.dial)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_Dist = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.label_Dist.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_Dist.setObjectName("label_Dist")
        self.horizontalLayout_4.addWidget(self.label_Dist)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayoutWidget_5 = QtGui.QWidget(Frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 210, 401, 51))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.label_R = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_R.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_R.setObjectName("label_R")
        self.horizontalLayout_5.addWidget(self.label_R)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(5, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.sliderR = QtGui.QSlider(self.verticalLayoutWidget_5)
        self.sliderR.setMinimum(0)
        self.sliderR.setMaximum(359)
        self.sliderR.setOrientation(QtCore.Qt.Horizontal)
        self.sliderR.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sliderR.setTickInterval(5)
        self.sliderR.setObjectName("sliderR")
        self.verticalLayout_5.addWidget(self.sliderR)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        Frame.setWindowTitle(QtGui.QApplication.translate("Frame", "Virtual Sensor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Frame", "X-Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_X.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Frame", "Y-Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Y.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Frame", "Z-Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Z.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Connect.setText(QtGui.QApplication.translate("Frame", "Announce", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Frame", "Distance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Dist.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Frame", "Rotation:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_R.setText(QtGui.QApplication.translate("Frame", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Frame", "°", None, QtGui.QApplication.UnicodeUTF8))
